- name: Values declare in playbook (local)
  become: yes
  hosts: localhost
  connection: local
  vars:
    course: DevOps
    duration: 2 months
    trainer: Eswar

  tasks:
    - name: Printing the courses (local)
      ansible.builtin.debug:
        msg: "Course name is: {{ course }}, Duration: {{ duration }}, Trainer: {{ trainer }}"
