- name: Install and enable nginx
  hosts: frontend
  tasks:
    - name: Install nginx package
      ansible.builtin.package:
        name: nginx
        state: present

    - name: Ensure nginx is started and enabled
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes
